# **Matrix Multiplication**

![](https://www.mathsisfun.com/algebra/images/matrix-multiply-ex1b.svg)

### You will work with a simple dummy data set that contains factory production values of electrical machinery parts for a corporation.

##### you will perform the following tasks:
- Load and study the data
- Extract production values as a matrix from the data
- Extract number of working days as a matrix from the data
- Multiply matrices

## **`Watch Video 5 : Matrix Multiplication`**

## Task 1 - Load and study the data

In [4]:
# Load "numpy" and "pandas" for manipulating numbers, vectors and data frames

import numpy as np
import pandas as pd

In [6]:
import numpy as np
import pandas as pd

# Read in the "Factory_Production.csv" file as a Pandas Data Frame
# Note: Make sure the code and the data are in the same folder or specify the appropriate path for the data
df = pd.read_csv('/content/sample_data/factory_data_indexed.csv')

In [7]:
# Take a brief look at the data frame using ".head()"
df.head()


,Factory,Generators,Motors,Cables,Days
0,A,8,17,232,352
1,B,6,20,203,348
2,C,10,16,187,337
3,D,7,24,218,357
4,E,13,13,256,362


#### Feature Description:
This data set contains the production values of power units such as generators, motors and cables of different factories belonging to the same corporation.

- Factory = unique label assigned to a factory unit for the purpose of identification
- Generators = number of generators produced by the factory in a day
- Motors = number of motors produced by the factory in a day
- Cables = number of cables produced by the factory in a day
- Days = number of working days of the factory in a year

##### Study its features such as:
- The number of factory units
- The number of machine parts
- The ranges of production values

In [8]:
# Check the dimensions of the data frame using ".shape"

df.shape

(10, 5)

In [9]:
# View basic information about the data frame using ".info()"
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Factory     10 non-null     object
 1   Generators  10 non-null     int64 
 2   Motors      10 non-null     int64 
 3   Cables      10 non-null     int64 
 4   Days        10 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 532.0+ bytes


In [10]:
# View a statistical summary of the data frame using ".describe()"
# Note: Use ".transpose()" to make the summary easier to read

df.describe()

,Generators,Motors,Cables,Days
count,10.000000,10.000000,10.000000,10.000000
mean,8.900000,17.800000,217.100000,349.600000
std,2.601282,3.521363,21.377298,8.983936
min,5.000000,13.000000,187.000000,337.000000
25%,7.250000,15.250000,203.500000,342.750000
50%,8.500000,17.500000,214.000000,350.000000
75%,10.750000,19.750000,230.250000,356.500000
max,13.000000,24.000000,256.000000,362.000000


##### Observations

- There are 10 rows and 4 columns
- The first 3 columns contain the production values of generators, motors and cables
- The fourth column contains the number of working days of the factories

## Task 2 - Extract production values as a matrix from the data

- The factory production values for each factory are contained in the "Generators", "Motors" and "Cables" features
- These production values will form a 10 x 3 matrix (considering all factories)

In [16]:
# Drop the "Days" and "Factory" columns from the data frame using ".drop()" and save the data in a new data frame called "df_prod"
df_prod = df.drop(['Days', 'Factory'], axis=1)

In [17]:
# Take a brief look at the data frame "df_prod" using ".head()"
df_prod.head()


,Generators,Motors,Cables
0,8,17,232
1,6,20,203
2,10,16,187
3,7,24,218
4,13,13,256


In [18]:
# Convert the "df_pod" data frame into a matrix using "np.matrix()" and call the matrix "mat_prod"
mat_prod = np.matrix(df_prod)


In [19]:
# Print the matrix "mat_prod"

print(mat_prod)

[[  8  17 232]
 [  6  20 203]
 [ 10  16 187]
 [  7  24 218]
 [ 13  13 256]
 [  9  18 210]
 [ 11  15 195]
 [  5  22 225]
 [ 12  14 240]
 [  8  19 205]]


In [20]:
# Check the dimensions of the "mat_prod" matrix using ".shape"
mat_prod.shape


(10, 3)

##### Observations

- The factory production values of generators, motors and cables of the 10 factories is a 10 x 3 matrix.
- The Numpy Matrix holds only values and does not have any indices

## Task 3 - Extract number of working days as a matrix from the data

- The number of working days for each factory is stored in the "Days" column of the data frame "df"
- These values will form a 10 x 1 matrix

In [21]:
# Convert the "Days" column of the data frame "df" into a matrix using "np.matrix()" and call the matrix "mat_days"
mat_days = np.matrix(df['Days'])


In [22]:
# Print the matrix "mat_days"
print(mat_days)


[[352 348 337 357 362 345 338 355 360 342]]


In [23]:
# Check the dimensions of the "mat_days" matrix using ".shape"

mat_days.shape

(1, 10)

##### Observations

- The number of working days of all the factories is in the form of a 1 x 10 matrix
- The Numpy Matrix holds only values and does not have any indices

## Task 4 - Multiply matrices

- The factory production values of generators, motors and cables of the 10 factories is a 10 x 3 matrix
- The number of working days of all the factories is in the form of a 1 x 10 matrix
- The product of these two matrices is equal to the linear combination of the production values vectors scaled by the number of working days

![](https://www.basic-mathematics.com/images/multiply-matrices.png)

In [25]:
# Multiply the "mat_prod" matrix by the "mat_days" matrix
# Note: The order of multiplication matters
# Note: Multiply the matrices using "mat_days * mat_prod"

mat_days * mat_prod

matrix([[ 31133,  62238, 760570]])

In [27]:
# Create a Pandas Series called "total" with index as "df_prod.columns" and data as the product of the two matrices
# Note: You will have to convert the resultant matrix into an array using "np.array()" and then extract out only the list
total = pd.Series(data=np.array(mat_days * mat_prod).flatten(), index=df_prod.columns)

In [28]:
# Print the "total" series

print(total)

Generators     31133
Motors         62238
Cables        760570
dtype: int64


##### Observations

- The corporation produces 30355 generators in a year
- The corporation produces 56602 motors in a year
- The corporation produces 708048 cables in a year

### Conclusions

- From the factory production data, we can calculate the total production of the corporation
- We can treat the production values of all the factories as a matrix
- We can treat the number of working days of factories as a matrix
- The product of the two matrices is equal to the linear combination of the factory production values scaled by their number of working days
- We can multiply the two matrices to calculate the total production

# **FEEDBACK**

https://forms.zohopublic.in/cloudyml/form/CloudyMLStatisticsFeedbackForm/formperma/WV946wnf0sDM_tOlH87RxZR9yMceKWGrtuPOyXzzCRc